### ISSUE TITLE
Talk category does not update

### ISSUE THREAD

**Issue by kaymckelly** [IACR/program-editor#135]
Any time you edit or drag a talk into a category, the category should change. Also, in the talk editor, the select for the category isn't properly initialized.

**Comment by kaymckelly** [comment]
TODO: go in and document issues more thoroughly; write a plan as to how to address it; incorporate changes after code review.

**Comment by kmccurley** [comment]
In retrospect I believe we should remove "category" from the talk part of the schema, and don't make any attempt to update it. The categories are only used for display on the left side, and only as a mechanism to organize talks. There is no need to have the talk have a reference to its category, and the way it is done now (by name rather than ID) is simply wrong.

**Comment by kmccurley** [comment]
We should therefore remove "category" from talk in the schema. That would also move it from the talk editor (except possibly when creating a new talk).
