### ISSUE TITLE
Delete session button doesn't work

### ISSUE THREAD

**Issue by kaymckelly** [IACR/program-editor#186]
If a session is dual track and has talks and you attempt to delete the session, nothing happens.

**Comment by kaymckelly** [comment]
Further testing: if session is dual track but the one you're trying to delete does not allow talks, then the delete does work.

**Comment by kaymckelly** [comment]
Cannot delete session if single track (with/without allowed talks) but session is deleted if time slot is deleted. Is this expected behavior?

**Comment by kmccurley** [comment]
If a session is single-track, then it doesn't make sense to delete the session without deleting the timeslot, since you can't have a timeslot without a session. You can still delete the timeslot in this case, but maybe we should also allow someone to delete the session (and thereby delete the timeslot as well).

I was able to delete a dual session, so we'll need to investigate this.

**Comment by kaymckelly** [comment]
Kay made an error and cannot recreate the issue with dual track. The single track case could use better documentation for the user (e.g. some text about deleting the time slot instead of the session).
